config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    member do |variable|
      get "like", to: "posts#upvote"
      get "dislike", to: "posts#downvote"
    end
    resources :comments
  end

  root 'posts#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  has_many :comment

  has_attached_file :image, :styles => { :medium => "700x400#", :small => "350x250>" }, :default_url => "missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.create(params[:comment].permit(:content))
    @comment.user_id = current_user.id
    @comment.post_id = @post.id

    if @comment.save
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action  :find_post, only:  [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action  :authenticate_user!, except: [:index, :show]
  respond_to :html, :json, :xml

  def index
    @posts = Post.all.order("created_at DESC")
    respond_to do |format|
      format.html
      format.json {render json: @posts}
    end
  end

  def show
    #@post = Post.find(params[:id])
    @comments = Comment.where(post_id: @post)
    respond_to do |format|
      format.html {@comments = Comment.where(post_id: @post)}
      format.json {render json: @post}
    end
  end
  #Responsible for rendering a form to create a new post Http GET Method
  def new
    @post = current_user.posts.build
  end
  #Responsible for creating the post inside the db Http POST Method
  def create
    @post = current_user.posts.build(post_params)
      if @post.save
        redirect_to @post
      else
        render 'new'
      end

  end
  #responsible for interacting with the model db Http PUT Method
  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end
  #responsible for rendering the view Http GET Method
  def edit

  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  def upvote
    @post.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @post.downvote_by current_user
    redirect_to :back
  end

  private
    def find_post
      @post = Post.find(params[:id])
    end

    def post_params
        params.require(:post).permit(:title, :link, :description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.haml
= simple_form_for([@post, @comments.build], :html=> { class: "ui reply form" } ) do |f|
  .field
    = f.input :content, label: "Reply to thread"

  = f.button :submit, label: "Add Comment", class: "ui primary submit labeled button"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Theactivist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
  = f.input :image
  = f.input :title
  = f.input :link
  = f.input :description

  = f.button :submit

app/views/posts/edit.html.haml
%h1 Edit post

=render 'form'

app/views/posts/index.html.haml
- @posts.each do |post|
  = link_to (image_tag post.image.url(:small))
  %h2= link_to post.title, post
  %p
    = post.comment.count
    Comments
  %p
    = post.get_likes.count
    Likes
= link_to "Add new", new_post_path

app/views/posts/new.html.haml
%h1 Add new post
= render 'form'

app/views/posts/show.html.haml
= image_tag @post.image.url(:medium)
%h1= @post.title
%p= @post.link
%p= @post.description
%p= @post.user.name
%p
  = @post.get_upvotes.size
  Likes
%p
  = @post.get_downvotes.size
  Dislikes
=link_to "Like", like_post_path(@post), method: :get
=link_to "Dislike", dislike_post_path(@post), method: :get
.ui.comments
  %h2.ui.dividing.header= pluralize(@comments.count, "Comment")
  - @comments.each do |comment|
    .comment
      %a.avatar
        = image_tag "user.png"
      .content
        %a.author= comment.user.name
        .metadata
          %span.date= comment.created_at
        .text= comment.content

  = render 'comments/form'
=link_to 'edit', edit_post_path
=link_to 'delete', post_path(@post), method: :delete, data:{ confirm: "Are you sure?" }

=link_to 'Home', root_path